### ISSUE TITLE
Multi-part CTRL selection problem

### ISSUE THREAD

**Issue by beefeater7** [ufb/Textmarker#66] opened 2019-06-16 17:58 UTC
As Firefox supports the selection of many disparate pieces of text on the page, I figure it should translate to highlights nicely. Instead the whole segment between the first selection and the last is highlighted.

The desired behavior would aid us in summarizing the contents of a piece of text, for instance. The mark entries could be formatted with [...] as separators, if that's practical. 

The desired:
![Screenshot_2019-06-16 Screenshot](https://user-images.githubusercontent.com/10468970/59567667-ff3d2180-905f-11e9-8e1b-4e1034276e80.png)

Currently:
![Screenshot_2019-06-16 Screenshot(1)](https://user-images.githubusercontent.com/10468970/59567680-2a277580-9060-11e9-86d8-96cd7e5cf556.png)

**Comment by ufb** [comment] 2019-06-16 18:37
Hi,

> The mark entries could be formatted with [...] as separators

This is not how Textmarker works.
A mark has to contain the highlighted text with no additional characters added (i.e. `[...]`) and meta infos about the relative position of the text in order to find the corresponding passage on page reload.

Sorry for having to disappoint you, but while it is theoretically possible to achieve the desired behavior it would take a huge amount of time, since the whole core, the whole way Textmarker works, would have to be rewritten. And it would have to be tested extensively to make sure of backwards-compatibility to older history entries.

Textmarker is converting disjointed text ranges to a single one by purpose, because highlighting only the parts of the text ranges can also be achieved by pressing key `M` (or one of the other highlighting methods available) after each disparate selection -> so, instead of selecting multiple text passages and then highlight them you can highlight after each selection, after all it's just one additional key-press for each selection, which seems acceptable.

**One important hint:** Your screenshot suggests that this is from a page that constantly changes its content. If so: Please note that Textmarker can only indirectly find the correct text passages after page reload (using meta infos about their position, as mentioned above), which means that the restoration of your highlights will most likely fail:
One example: You highlight the uppermost text passage and save it. Textmarker will store its relative position, which includes something like "first element of parent element". In case the page is updated before your next visit, so that this passage is no longer the first but the second element (because a new text passage was added), Textmarker will find the correct passage, but won't restore it, because it wouldn't meet the meta infos. Aborting such a mark is necessary, because it could otherwise mess up all other marks (i.e. because one mark's position could be dependent on another mark's position).

**Comment by ufb** [comment] 2019-07-02 11:56
@beefeater7 
Just a question for clarification: Is it important to you to have the disjoint parts of your selection saved as a single "mark"? Or would it be OK if Textmarker is just treating them as separate marks (as if you had done them successively)?
The former is not possible (see reasons above), the latter would be.
There still remains a problem though: Even though Textmarker can recognize disjoint selection parts (using `getSelection().rangeCount` and `getSelection().getRangeAt(<index>)`) it would be complicated to tell if this disjoint is something the user did by purpose or if it's because there is markup interrupting the ranges - for the latter the expected behavior would be to treat it as single mark (=the current procedure).
I will keep this issue open for now in case you or other users want to share their ideas, but this feature request will most likely become a "won't do".
Side note: Textmarker 5.0.0 will be released soon.

**Comment by beefeater7** [comment] 2019-07-02 14:58
I've thought a bit about the stuff you told me.

To me, it seems like a two-part problem. You store the marks in plain text without formatting and associate them with the corresponding range. Then you relay the info in the marks and notes list. Database, presentation.

It makes more sense to me if you divide entries with mark up interruptions, because they don't display right in the list anyway. Line breaks between headers and text, or multiple paragraphs are not presented. This is also where an insert like [...] would belong, in the presentation layer, but there is none yet. 

So I say go ahead and break up the text. Reasonable exception for sub-tags like strong, em, et cetera. You'd need to start grouping entries to pull off the presentation layer, but it could pay off as a future endeavor.

About that transcript, it's just a plain text caption from YouTube. However, I do have that setting activated, to keep the page as it was. That should prevent breakage, right?

**Comment by ufb** [comment] 2019-07-02 15:15
> You store the marks in plain text without formatting and associate them with the corresponding range

HTML elements same as javascript objects like the ranges have no persistence across reloads, so it's not possible to store references to them;)

> Line breaks between headers and text, or multiple paragraphs are not presented

It's true that Textmarker currently won't preserve line-breaks in storage - but this has been taken care of and with the new version 5.0.0 coming up soon line-breaks will be stored - and therefore also presented.

> You'd need to start grouping entries to pull off the presentation layer

By "entries" you mean marks? "Entries" is what I call the whole presentation of all highlights, notes etc. of a website - so the history page is listing entries and each entry has a list of marks.

> I do have that setting activated, to keep the page as it was. That should prevent breakage, right?

No. The setting you are probably referring to won't keep pages as they were. It will only lead to a different restoration process, which uses a different set of meta infos stored with each mark/highlight. It's just to "tell" Textmarker: "Hey, I'm sure this page will never change it's content, so treat it accordingly". You need to make sure on your own that a page stays immutable - as explained in the manual you can achieve that by downloading a website or using a service like the FF-built-in Pocket or any third-party-service of your choice. There is no server behind Textmarker - everything stays on your own machine.

I will read your post more carefully later on (have an appointment now...)

**Comment by ufb** [comment] 2019-07-03 14:01
OK, so if I understood you correctly it would be sufficient for you if Textmarker would preserve line-breaks? And is it fine with you that you'd have to click key M (or whichever highlighting method you are using) on each disparate selection (range)? If so, then work is done and you just have to wait a few days for upcoming release ;)

**Comment by ufb** [comment] 2019-07-13 17:21
Well, at this point I can only guess that this issue was mainly about missing preservation of line-breaks.
This has been solved with v5.
And preserving disjoint selection ranges (either by creating multiple highlights or by changing the way highlights are being stored) won't be worked on (see reasons above).

**Closed by ufb** 2019-07-13 17:21 UTC
Labels: enhancement, needs further infos
